/**
 * Offline, one-time driver: generate Pre-K picture hints for scavenger-hunt clues.
 *
 * Pre-K is the only reading level that shows pictures, so we image every `pre_k`
 * prompt that lacks an `image_url`. Re-runnable / idempotent (already-imaged prompts
 * are skipped). After generating, it emits a migration with the URL writes so other
 * environments replay them without re-paying for generation (spec §5.2).
 *
 * Requires SUPABASE_SERVICE_ROLE_KEY + NEXT_PUBLIC_SUPABASE_URL + OPENAI_API_KEY.
 * NOT invoked during gameplay.
 *
 * Run (Node 20+):
 *   npx tsx --env-file=.env.local scripts/generate-scavenger-prompt-images.ts
 *   # add --dry-run to preview which prompts would be imaged, without calling DALL-E
 */
import { createClient } from '@supabase/supabase-js'
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import {
  generatePromptImage,
  type PromptImageRow,
} from '../lib/services/scavenger-prompt-image-generator'
import { extractHintColor } from '../lib/services/scavenger-color-hints'

const DRY_RUN = process.argv.includes('--dry-run')

function ts(): string {
  // YYYYMMDDHHMMSS — matches the supabase migration naming convention.
  return new Date()
    .toISOString()
    .replace(/[-:T]/g, '')
    .slice(0, 14)
}

function sqlEscape(s: string): string {
  return s.replace(/'/g, "''")
}

async function main() {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY
  if (!supabaseUrl || !serviceKey) {
    console.error('Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY')
    process.exit(1)
  }
  const supabase = createClient(supabaseUrl, serviceKey)

  const { data: prompts, error } = await supabase
    .from('scavenger_hunt_prompts')
    .select('id, prompt_text, target_description, example_objects, category')
    .eq('reading_level', 'pre_k')
    .is('image_url', null)

  if (error) {
    console.error('Failed to load prompts:', error.message)
    process.exit(1)
  }

  // Single-color clues ("Find something pink") show a plain color swatch in the UI,
  // not a picture — an AI image of one object would mislead a non-reader. Skip them.
  const all = (prompts || []) as (PromptImageRow & { category: string | null })[]
  const skipped = all.filter((r) => extractHintColor(r.prompt_text, r.category))
  const rows: PromptImageRow[] = all.filter(
    (r) => !extractHintColor(r.prompt_text, r.category)
  )
  if (skipped.length > 0) {
    console.log(`Skipping ${skipped.length} color clue(s) (rendered as a swatch).`)
  }
  console.log(`${rows.length} pre_k prompt(s) need an image.`)
  if (rows.length === 0) return

  if (DRY_RUN) {
    for (const r of rows) console.log(`  - [${r.id}] ${r.prompt_text}`)
    console.log('Dry run — no images generated.')
    return
  }

  const writes: { id: string; url: string; path: string }[] = []
  let failures = 0

  for (let i = 0; i < rows.length; i++) {
    const row = rows[i]
    process.stdout.write(`(${i + 1}/${rows.length}) ${row.prompt_text} … `)
    const result = await generatePromptImage(row)
    if (result.success && result.imageUrl && result.storagePath) {
      writes.push({ id: row.id, url: result.imageUrl, path: result.storagePath })
      console.log('ok')
    } else {
      failures++
      console.log(`FAILED: ${result.error}`)
    }
    // Gentle pacing to stay clear of image-generation rate limits.
    await new Promise((r) => setTimeout(r, 1500))
  }

  console.log(`\nGenerated ${writes.length}, failed ${failures}.`)

  if (writes.length > 0) {
    // Emit a replayable migration of the URL writes (spec §5.2). image_storage_path
    // is identical per environment; image_url differs by Supabase project host, so a
    // re-run in another env can regenerate — but committing these lets shared
    // environments skip generation entirely.
    const lines = writes.map(
      (w) =>
        `UPDATE scavenger_hunt_prompts SET image_url = '${sqlEscape(w.url)}', ` +
        `image_storage_path = '${sqlEscape(w.path)}' WHERE id = '${w.id}';`
    )
    const header =
      '-- Generated by scripts/generate-scavenger-prompt-images.ts\n' +
      '-- Pre-K picture-hint URL writes (replayable; safe to re-run).\n\n'
    const file = join(
      process.cwd(),
      'supabase',
      'migrations',
      `${ts()}_set_scavenger_prek_image_urls.sql`
    )
    writeFileSync(file, header + lines.join('\n') + '\n')
    console.log(`Wrote migration: ${file}`)
  }
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
